"""empty message

Revision ID: 089810f31a66
Revises: 
Create Date: 2020-09-08 17:20:58.235377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089810f31a66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celestial_bodies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('celestial_body_type', sa.String(), nullable=True),
    sa.Column('gravity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('celestial_bodies')
    # ### end Alembic commands ###
