"""empty message

Revision ID: 4e041c5da440
Revises: 089810f31a66
Create Date: 2020-09-08 17:41:49.948034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e041c5da440'
down_revision = '089810f31a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('landmark_type', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('celestial_body_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['celestial_body_id'], ['celestial_bodies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('landmark')
    # ### end Alembic commands ###
