"""empty message

Revision ID: 78361b002882
Revises: 4e041c5da440
Create Date: 2020-09-08 17:52:29.534625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78361b002882'
down_revision = '4e041c5da440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_digest', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
