"""empty message

Revision ID: a3646366838f
Revises: fd869230502f
Create Date: 2020-09-08 18:20:20.819348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3646366838f'
down_revision = 'fd869230502f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voyages',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('celestial_bodies_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['celestial_bodies_id'], ['celestial_bodies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'celestial_bodies_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voyages')
    # ### end Alembic commands ###
