"""empty message

Revision ID: f49553f399f3
Revises: 
Create Date: 2020-09-09 15:41:57.916553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49553f399f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celestial_bodies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('celestial_body_type', sa.String(), nullable=True),
    sa.Column('gravity', sa.Float(), nullable=True),
    sa.Column('planet_day', sa.Float(), nullable=True),
    sa.Column('planet_year', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_digest', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('landmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('landmark_type', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('celestial_body_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['celestial_body_id'], ['celestial_bodies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voyages',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('celestial_bodies_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['celestial_bodies_id'], ['celestial_bodies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'celestial_bodies_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voyages')
    op.drop_table('passengers')
    op.drop_table('landmarks')
    op.drop_table('users')
    op.drop_table('celestial_bodies')
    # ### end Alembic commands ###
